//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.all2one.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Stringtable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stringtable() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Programme.all2one.Properties.Stringtable", typeof(Stringtable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Verschieben einer Datei. ähnelt.
        /// </summary>
        internal static string _0x0001c {
            get {
                return ResourceManager.GetString("0x0001c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei &quot;{0}&quot; kann nicht nach &quot;{1}&quot; verschoben werden.
        ///
        ///{2} ähnelt.
        /// </summary>
        internal static string _0x0001m {
            get {
                return ResourceManager.GetString("0x0001m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang abgeschlossen. ähnelt.
        /// </summary>
        internal static string _0x0002c {
            get {
                return ResourceManager.GetString("0x0002c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Vorgang wurde beendet.
        ///
        ///
        ///Zusammenfassung:
        ///
        ///Zu verschiebende Dateien:
        ///    {0}
        ///Verschobene Dateien:
        ///    {1}
        ///Übersprungene Dateien:
        ///    {2}
        ///Fehler beim Verschieben:
        ///    {3} ähnelt.
        /// </summary>
        internal static string _0x0002m {
            get {
                return ResourceManager.GetString("0x0002m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quellordner auswählen. ähnelt.
        /// </summary>
        internal static string _0x0003 {
            get {
                return ResourceManager.GetString("0x0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zielordner auswähelen. ähnelt.
        /// </summary>
        internal static string _0x0004 {
            get {
                return ResourceManager.GetString("0x0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte Aufgabe auswählen ähnelt.
        /// </summary>
        internal static string _0x0005c {
            get {
                return ResourceManager.GetString("0x0005c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde keine Aufgabe ausgewählt. Bitte wählen Sie aus, ob Dateien kopiert und/oder ein Index erstellt werden soll. ähnelt.
        /// </summary>
        internal static string _0x0005m {
            get {
                return ResourceManager.GetString("0x0005m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pfade nicht angegeben ähnelt.
        /// </summary>
        internal static string _0x0006c {
            get {
                return ResourceManager.GetString("0x0006c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quell- oder Zielverzeichniss sind nicht angegeben. ähnelt.
        /// </summary>
        internal static string _0x0006m {
            get {
                return ResourceManager.GetString("0x0006m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Index erstellen. ähnelt.
        /// </summary>
        internal static string _0x0007c {
            get {
                return ResourceManager.GetString("0x0007c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beim Erstellen des Index ist ein Fehler aufgetreten.
        ///
        ///{0}
        ///
        ///Weitere Fehlermeldungen dieser Art werden unterdrückt. ähnelt.
        /// </summary>
        internal static string _0x0007m {
            get {
                return ResourceManager.GetString("0x0007m", resourceCulture);
            }
        }
    }
}
